### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ankityadavhere** [ankityadavhere/url-shortener#4]
- [x] - move analytics to google analytics
- [x] - make analytics work with redirects
- [x] - refactor code
- [x] - enhance performance and redirect speeds
- [x] - update docs
- [x] - make new release && update package version

**Comment by ankityadavhere** [comment]
whoosh!
